### ISSUE TITLE
Publish on Homebrew?

### ISSUE THREAD

**Issue by martin-braun** [Peter-Schorn/SpotifyAPIServer#2]
I think it would be a cool option to provide the server as a package at brew.sh itself. Hosting the SpotifyAPIServer in a cloud, or using a shared instance is generally good for preventing token invalidation. I don't mind re-authenticating on every session though. I would really enjoy the option to host the SpotifyAPIServer locally from an official source that will be updated. The package should make use of the services API of Homebrew, so that it can be enabled/disabled at will. This would also require that environment variables can be read from a configuration file as well.

Could this be considered, please?

**Comment by Peter-Schorn** [comment]
> Hosting the SpotifyAPIServer in a cloud, or using a shared instance is generally good for preventing token invalidation.

Where/how the server is hosted should not affect whether or not the tokens become invalid. I don't understand what you're "preventing" based on how you host the server. I think you're making a mistake some how. 

The access token expires after an hour, and the refresh token only becomes invalid after you exchange it for a new refresh token. The access token can also become invalid if you retrieve a new access token and try to use the old access token. This can happen if you have multiple different instances of the same application (e.g., multiple instances of Soft Player) accessing the same local storage of the access/refresh token.

> I don't mind re-authenticating on every session though.

You should only ever need to open the authorization URL and approve the application once. After that, the access token can be refreshed as needed automatically in the background without any user input.

> I would really enjoy the option to host the SpotifyAPIServer locally from an official source that will be updated.

Github is the official source of this package. Every commit on master is stable. I still do not understand the benefit of publishing on Homebrew. You can clone, configure, and run this server automatically with a script already. You can automate the process of injecting environment variables as well.

**Comment by martin-braun** [comment]
Thanks for the education on the token logic. For some reason I thought otherwise because I experienced a different behavior on another app. After using your server for 2 days, I'm happy to see that my session is still valid, despite sleeping etc. 

That got me thinking about the necessity of having the server not embedded within SoftPlayer, wouldn't that make sense? You wouldn't need to host the server. Maybe you decided not to embed the server into SoftPlayer, because it be easier to setup for multiple devices?

I do agree on all points you made, but I still think it could be nicer by packaging software to a distribution platform such as Homebrew in general, solely for the auto updating and having less work on setting things up, in case the user doesn't want to use the version from the AppStore. 

However, even when you reject my request, I'm grateful nonetheless. This is a great piece of software you made and nobody stops somebody to do all the steps that I request. This is open-source after all.

**Comment by Peter-Schorn** [comment]
> That got me thinking about the necessity of having the server not embedded within SoftPlayer, wouldn't that make sense? You wouldn't need to host the server. Maybe you decided not to embed the server into SoftPlayer, because it be easier to setup for multiple devices?

Soft Player uses this server for security purposes. This server can securely store your client secret, as opposed to it being exposed in the front-end application. And, this server encrypts the refresh token. See also [here](https://peter-schorn.github.io/SpotifyAPI/documentation/spotifywebapi/additional-authorization-methods/).

I could, however, add a compilation condition to Soft Player that allows it to be used without a backend server.

**Comment by martin-braun** [comment]
> I could, however, add a compilation condition Soft Player that allows it to be used without a backend server.

This would nail it. Surely, the SoftPlayer wouldn't be as light-weight, but it would be fully contained without any external dependencies.

**Comment by Peter-Schorn** [comment]
> Surely, the SoftPlayer wouldn't be as light-weight

It would be just as light-weight. Eliminating the server doesn't require adding more code to soft player. The security of the server derives from the fact that it is hosted *on a server*, where a malicious actor cannot access it.

**Comment by Peter-Schorn** [comment]
> I could, however, add a compilation condition to Soft Player that allows it to be used without a backend server.

Done in [43e5553](https://github.com/Peter-Schorn/SoftPlayer/commit/43e55530c14f4f7c0a68bca96a856ee430e443ba#diff-1f50cafcc5ab8332f31960b4dd998e603bfde17904ca54b7df84998c2adc297bR169-R193).

Soft Player now supports user defaults for setting the authorization credentials as well.
